### PR TITLE
Added a few more links

### PR DESCRIPTION
**Pull request by svinkle**
…also fixed some weird spacing that was bugging me. 🙂

### CODE REVIEW

**Comment by scottaohara** [comment]
excellent adds!

only question I have is should books be on the list of people to follow?

There's this list [a11y courses & resources](https://github.com/mgifford/a11y-courses) that has courses, books, and other resources on it.  maybe cross link the two?

**Comment by svinkle** [comment]
@scottaohara, good question. Perhaps we could adjust the title of the document? Or, leave off and add somewhere else. Thoughts @joe-watkins?

That link should definitely be added to this list, though. 👍

**Comment by joe-watkins** [comment]
@svinkle Tnx for the awesome add. I've created a section for these additional resources.

@scottaohara Tnx for link to courses -- I've added that as well! :)

**Comment by svinkle** [comment]
Nice @joe-watkins! The new section looks great, good thinking. 🙌

**Pull request merged**
